#!/usr/bin/python3


"""Importing module for getting the argv and exit"""


import sys
ac = len(sys.argv)
if(ac != 2):
    sys.exit(f"Usage: {sys.argv[0]} <file>")


"""Finding natural factors of a number"""


def factorizer(n):
    if (n % 2 == 0):
        print("{}={}*{}".format(n, n//2, 2))
    else:
        for i in range(3, int(n**0.5) + 1, 2):
            if n % i == 0:
                break
        print("{}={}*{}".format(n, n//i, i))

"""Opening a test file containing test cases(n)"""


def file_open(file):
    with open(file) as f:
        for num in f:
            num = int(num)
            factorizer(num)
    f.close()

file_open(sys.argv[1])
